spring:
    docker:
        compose:
            enabled: true
            lifecycle-management: START_ONLY
            file: ../docker-compose.yml
    datasource:
        url: jdbc:postgresql://127.0.0.1:5432/paginated_reports
        username: postgres
        password: postgres
    sql:
        init:
            mode: ALWAYS
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

logging:
    level:
        root: ERROR
        org.springframework.web: DEBUG
        com.arcadia: DEBUG
        org.zalando.logbook: TRACE

logbook:
  include: /api/**
  filter.enabled: ${LOGBOOK_FILTER_ENABLED:true}
  format.style: json #other values are :http
  obfuscate.write.category: http.wire-log
  write:
    #chunk-size: ${LOGBOOK_CHUNK_SIZE:1000}
    #max-body-size: ${LOGBOOK_WRITE_MAX_BODY_SIZE:100000}
    level: ${LOGBOOK_WRITE_LEVEL:INFO}
