CREATE TABLE public.split_runs (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

  name VARCHAR(255) NOT NULL,

  -- Audit columns
  customer_id VARCHAR(50) NOT NULL,
  user_id VARCHAR(50) NOT NULL,

  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_by VARCHAR(50) NOT NULL,

  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_by VARCHAR(50) NOT NULL,

  deleted_at TIMESTAMP WITH TIME ZONE NULL,
  deleted_by VARCHAR(50) NULL

);
