spring:
    datasource:
        url: jdbc:postgresql://127.0.0.1:5432/paginated_reports
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
server:
    port: 8081